spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:

      format_sql: true
      show_sql: ${SHOW_SQL}
      jdbc:
        batch_size: 200
    open-in-view: false

  jwt:
    jwt-secret:  ${JWT_SECRET}
    header: ${HEADER}
    prefix: ${PREFIX}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
